#requires -version 5.1
<#
.SYNOPSIS
Safely archive and clean up Windows event logs for DWP endpoint operations.

.DESCRIPTION
This script archives eligible event logs and then clears them only when safe rules are met.
It supports dry-run reporting, per-operation error handling, timestamped logging, summary output,
rollback package restoration, and idempotent daily archiving.

.NOTES
- Cleanup only targets logs where the newest event is older than the cutoff date.
- If an archive for the same log and today's date already exists, that log is skipped.
- Rollback mode restores archive artifacts to a restore folder for retrieval/review.
#>

[CmdletBinding(DefaultParameterSetName = 'Cleanup')]
param(
    # Section 1: Cleanup parameters
    # Defines target logs and age threshold for cleanup mode.
    [Parameter(ParameterSetName = 'Cleanup')]
    [string[]]$LogName = @('Application', 'System'),

    [Parameter(ParameterSetName = 'Cleanup')]
    [ValidateRange(0, 3650)]
    [int]$OlderThanDays = 3,

    [Parameter(ParameterSetName = 'Cleanup')]
    [switch]$DryRun,

    # Section 2: Rollback parameters
    # Restores archived artifacts from a manifest generated by an earlier cleanup run.
    [Parameter(Mandatory = $true, ParameterSetName = 'Rollback')]
    [switch]$Rollback,

    [Parameter(Mandatory = $true, ParameterSetName = 'Rollback')]
    [ValidateNotNullOrEmpty()]
    [string]$RollbackManifestPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Section 3: Runtime paths and identifiers
# Creates stable paths under the script folder for logs, archives, and rollback metadata.
$scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Path $MyInvocation.MyCommand.Path -Parent }
$logRoot = Join-Path -Path $scriptRoot -ChildPath 'Logs'
$archiveRoot = Join-Path -Path $scriptRoot -ChildPath 'EventLogArchive'
$rollbackRoot = Join-Path -Path $scriptRoot -ChildPath 'EventLogRollbackStore'
$restoreRoot = Join-Path -Path $scriptRoot -ChildPath 'EventLogRestore'
$runId = '{0}-{1}' -f (Get-Date -Format 'yyyyMMdd-HHmmssfff'), $PID
$todayStamp = Get-Date -Format 'yyyyMMdd'
$logFile = Join-Path -Path $logRoot -ChildPath (('DWP-EventLog-Archive-Cleanup-{0}.log' -f $runId))

foreach ($folder in @($logRoot, $archiveRoot, $rollbackRoot, $restoreRoot)) {
    if (-not (Test-Path -LiteralPath $folder)) {
        New-Item -Path $folder -ItemType Directory -Force | Out-Null
    }
}

# Section 4: Logging helper
# Writes all script actions to console and a timestamped log file.
function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [ValidateSet('INFO', 'WARN', 'ERROR')]
        [string]$Level = 'INFO'
    )

    $entry = '{0} [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -Path $logFile -Value $entry
    Write-Host $entry
}

# Section 5: Utility helpers
# Provides reusable operations for safe path generation and command execution.
function Get-SafeLogFileName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    return ([System.Text.RegularExpressions.Regex]::Replace($Name, '[^A-Za-z0-9._-]', '_')).Trim('_')
}

function Resolve-FullPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$InputPath
    )

    return [System.IO.Path]::GetFullPath($InputPath)
}

function Invoke-WevtUtil {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments
    )

    $quotedArguments = $Arguments | ForEach-Object {
        if ($_ -match '\s') {
            '"{0}"' -f $_
        } else {
            $_
        }
    }

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName = 'wevtutil.exe'
    $psi.Arguments = ($quotedArguments -join ' ')
    $psi.RedirectStandardError = $true
    $psi.RedirectStandardOutput = $true
    $psi.UseShellExecute = $false
    $psi.CreateNoWindow = $true

    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $psi
    [void]$process.Start()
    $stdout = $process.StandardOutput.ReadToEnd()
    $stderr = $process.StandardError.ReadToEnd()
    $process.WaitForExit()

    return [pscustomobject]@{
        ExitCode = $process.ExitCode
        StdOut   = $stdout
        StdErr   = $stderr
    }
}

# Section 6: Cleanup mode implementation
# Archives and clears only logs whose newest event is older than the configured cutoff.
function Invoke-EventLogCleanup {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$TargetLogs,

        [Parameter(Mandatory = $true)]
        [int]$AgeDays,

        [Parameter(Mandatory = $true)]
        [bool]$IsDryRun
    )

    $cutoff = (Get-Date).AddDays(-$AgeDays)
    $batchRoot = Join-Path -Path $rollbackRoot -ChildPath (('Batch-{0}' -f $runId))
    $manifestPath = Join-Path -Path $batchRoot -ChildPath 'RollbackManifest.csv'
    $manifestInitialized = $false

    if (-not $IsDryRun) {
        New-Item -Path $batchRoot -ItemType Directory -Force | Out-Null
    }

    $summary = [ordered]@{
        Mode                   = if ($IsDryRun) { 'DryRun' } else { 'Cleanup' }
        CutoffTime             = $cutoff
        LogsRequested          = @($TargetLogs).Count
        LogsProcessed          = 0
        LogsSkippedIdempotent  = 0
        LogsSkippedRecentData  = 0
        LogsSkippedEmpty       = 0
        LogsArchived           = 0
        LogsCleared            = 0
        TotalRecordsToDelete   = 0
        OperationErrors        = 0
    }

    Write-Log -Message ('Starting {0}. OlderThanDays={1}. Cutoff={2}' -f $summary.Mode, $AgeDays, $cutoff)

    foreach ($logNameValue in $TargetLogs) {
        $summary.LogsProcessed++
        $safeName = Get-SafeLogFileName -Name $logNameValue
        if ([string]::IsNullOrWhiteSpace($safeName)) {
            $safeName = 'Log'
        }

        $archivePath = Join-Path -Path $archiveRoot -ChildPath (('{0}-{1}.evtx' -f $safeName, $todayStamp))
        $clearBackupPath = Join-Path -Path $batchRoot -ChildPath (('{0}-clearbackup-{1}.evtx' -f $safeName, $runId))

        if (Test-Path -LiteralPath $archivePath) {
            $summary.LogsSkippedIdempotent++
            Write-Log -Level 'INFO' -Message ('Skipping log due to existing archive for today: {0} ({1})' -f $logNameValue, $archivePath)
            continue
        }

        $logInfo = $null
        try {
            $logInfo = Get-WinEvent -ListLog $logNameValue -ErrorAction Stop
        } catch {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Failed to read log metadata for {0}. Error: {1}' -f $logNameValue, $_.Exception.Message)
            continue
        }

        if ($null -eq $logInfo -or [int64]$logInfo.RecordCount -le 0) {
            $summary.LogsSkippedEmpty++
            Write-Log -Message ('Skipping empty log: {0}' -f $logNameValue)
            continue
        }

        $newestEvent = $null
        try {
            $newestEvent = Get-WinEvent -FilterHashtable @{ LogName = $logNameValue } -MaxEvents 1 -ErrorAction Stop
        } catch {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Failed to read newest event for {0}. Error: {1}' -f $logNameValue, $_.Exception.Message)
            continue
        }

        if ($null -eq $newestEvent) {
            $summary.LogsSkippedEmpty++
            Write-Log -Message ('Skipping log with no readable events: {0}' -f $logNameValue)
            continue
        }

        if ($newestEvent.TimeCreated -gt $cutoff) {
            $summary.LogsSkippedRecentData++
            Write-Log -Message ('Skipping log with recent events newer than cutoff: {0}' -f $logNameValue)
            continue
        }

        $recordsToDelete = [int64]$logInfo.RecordCount
        $summary.TotalRecordsToDelete += $recordsToDelete

        if ($IsDryRun) {
            Write-Log -Message ('DRY-RUN would clear log: {0}. RecordCount={1}' -f $logNameValue, $recordsToDelete)
            continue
        }

        $archiveResult = $null
        try {
            $archiveResult = Invoke-WevtUtil -Arguments @('epl', $logNameValue, $archivePath)
        } catch {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Archive command failed to execute for {0}. Error: {1}' -f $logNameValue, $_.Exception.Message)
            continue
        }

        if ($archiveResult.ExitCode -ne 0) {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Archive failed for {0}. wevtutil exit code {1}. StdErr: {2}' -f $logNameValue, $archiveResult.ExitCode, $archiveResult.StdErr)
            continue
        }

        $summary.LogsArchived++
        Write-Log -Message ('Archived log: {0} -> {1}' -f $logNameValue, $archivePath)

        $clearResult = $null
        try {
            $clearResult = Invoke-WevtUtil -Arguments @('cl', $logNameValue, ('/bu:{0}' -f $clearBackupPath))
        } catch {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Clear command failed to execute for {0}. Error: {1}' -f $logNameValue, $_.Exception.Message)
            continue
        }

        if ($clearResult.ExitCode -ne 0) {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Clear failed for {0}. wevtutil exit code {1}. StdErr: {2}' -f $logNameValue, $clearResult.ExitCode, $clearResult.StdErr)
            continue
        }

        $summary.LogsCleared++
        Write-Log -Message ('Cleared log: {0}. Backup file: {1}' -f $logNameValue, $clearBackupPath)

        $manifestRecord = [pscustomobject]@{
            LogName         = $logNameValue
            ArchivePath     = $archivePath
            ClearBackupPath = $clearBackupPath
            BatchRoot       = $batchRoot
            ClearedAt       = Get-Date -Format 's'
            RecordCount     = $recordsToDelete
        }

        try {
            if (-not $manifestInitialized) {
                $manifestRecord | Export-Csv -Path $manifestPath -NoTypeInformation
                $manifestInitialized = $true
            } else {
                $manifestRecord | Export-Csv -Path $manifestPath -NoTypeInformation -Append
            }
        } catch {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Failed to write rollback manifest entry for {0}. Error: {1}' -f $logNameValue, $_.Exception.Message)
        }
    }

    if (-not $IsDryRun -and -not $manifestInitialized) {
        try {
            @() | Export-Csv -Path $manifestPath -NoTypeInformation
        } catch {
            $summary.OperationErrors++
            Write-Log -Level 'ERROR' -Message ('Failed to create empty rollback manifest. Error: {0}' -f $_.Exception.Message)
        }
    }

    Write-Log -Message ('Log file saved to: {0}' -f $logFile)
    if (-not $IsDryRun) {
        Write-Log -Message ('Rollback manifest saved to: {0}' -f $manifestPath)
    }

    Write-Host ''
    Write-Host 'Event Log Cleanup Summary'
    Write-Host '-------------------------'
    Write-Host ('Mode                  : {0}' -f $summary.Mode)
    Write-Host ('Cutoff Time           : {0}' -f $summary.CutoffTime)
    Write-Host ('Logs Requested        : {0}' -f $summary.LogsRequested)
    Write-Host ('Logs Processed        : {0}' -f $summary.LogsProcessed)
    Write-Host ('Logs Skipped (Today)  : {0}' -f $summary.LogsSkippedIdempotent)
    Write-Host ('Logs Skipped (Recent) : {0}' -f $summary.LogsSkippedRecentData)
    Write-Host ('Logs Skipped (Empty)  : {0}' -f $summary.LogsSkippedEmpty)
    Write-Host ('Logs Archived         : {0}' -f $summary.LogsArchived)
    Write-Host ('Logs Cleared          : {0}' -f $summary.LogsCleared)
    Write-Host ('Records To Delete     : {0}' -f $summary.TotalRecordsToDelete)
    Write-Host ('Operation Errors      : {0}' -f $summary.OperationErrors)
    if (-not $IsDryRun) {
        Write-Host ('Rollback Manifest     : {0}' -f $manifestPath)
    }
    Write-Host ('Log File              : {0}' -f $logFile)

    return [pscustomobject]@{
        Summary      = $summary
        ManifestPath = if ($IsDryRun) { $null } else { $manifestPath }
        LogFile      = $logFile
    }
}

# Section 7: Rollback mode implementation
# Restores archived artifacts from a manifest into a dated restore folder.
function Invoke-EventLogRollback {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Manifest
    )

    $manifestPath = Resolve-FullPath -InputPath $Manifest
    Write-Log -Message ('Starting rollback package restore using manifest: {0}' -f $manifestPath)

    if (-not (Test-Path -LiteralPath $manifestPath)) {
        throw 'Rollback manifest not found.'
    }

    $records = @()
    try {
        $records = @(Import-Csv -Path $manifestPath)
    } catch {
        throw ('Failed to read rollback manifest. Error: {0}' -f $_.Exception.Message)
    }

    $restoreBatchRoot = Join-Path -Path $restoreRoot -ChildPath (('Restore-{0}' -f $runId))
    New-Item -Path $restoreBatchRoot -ItemType Directory -Force | Out-Null

    $summary = [ordered]@{
        RecordsRead         = @($records).Count
        FilesRestored       = 0
        AlreadyRestored     = 0
        MissingSourceFiles  = 0
        RestoreErrors       = 0
    }

    foreach ($record in $records) {
        foreach ($fieldName in @('ArchivePath', 'ClearBackupPath')) {
            $sourcePath = $record.$fieldName

            if ([string]::IsNullOrWhiteSpace($sourcePath)) {
                continue
            }

            $resolvedSource = Resolve-FullPath -InputPath $sourcePath
            if (-not (Test-Path -LiteralPath $resolvedSource)) {
                $summary.MissingSourceFiles++
                Write-Log -Level 'WARN' -Message ('Rollback source missing: {0}' -f $resolvedSource)
                continue
            }

            $destinationPath = Join-Path -Path $restoreBatchRoot -ChildPath (Split-Path -Path $resolvedSource -Leaf)
            if (Test-Path -LiteralPath $destinationPath) {
                $summary.AlreadyRestored++
                Write-Log -Message ('Rollback file already restored in this batch: {0}' -f $destinationPath)
                continue
            }

            try {
                Copy-Item -LiteralPath $resolvedSource -Destination $destinationPath -Force -ErrorAction Stop
                $summary.FilesRestored++
                Write-Log -Message ('Restored rollback artifact: {0} -> {1}' -f $resolvedSource, $destinationPath)
            } catch {
                $summary.RestoreErrors++
                Write-Log -Level 'ERROR' -Message ('Failed to restore artifact: {0}. Error: {1}' -f $resolvedSource, $_.Exception.Message)
            }
        }
    }

    Write-Log -Message ('Log file saved to: {0}' -f $logFile)

    Write-Host ''
    Write-Host 'Event Log Rollback Summary'
    Write-Host '--------------------------'
    Write-Host ('Records Read        : {0}' -f $summary.RecordsRead)
    Write-Host ('Files Restored      : {0}' -f $summary.FilesRestored)
    Write-Host ('Already Restored    : {0}' -f $summary.AlreadyRestored)
    Write-Host ('Missing Source Files: {0}' -f $summary.MissingSourceFiles)
    Write-Host ('Restore Errors      : {0}' -f $summary.RestoreErrors)
    Write-Host ('Restore Folder      : {0}' -f $restoreBatchRoot)
    Write-Host ('Log File            : {0}' -f $logFile)

    return [pscustomobject]@{
        Summary       = $summary
        RestoreFolder = $restoreBatchRoot
        LogFile       = $logFile
    }
}

# Section 8: Main execution controller
# Dispatches script flow to cleanup mode or rollback mode.
try {
    if ($PSCmdlet.ParameterSetName -eq 'Rollback') {
        Invoke-EventLogRollback -Manifest $RollbackManifestPath | Out-Null
    } else {
        Invoke-EventLogCleanup -TargetLogs $LogName -AgeDays $OlderThanDays -IsDryRun $DryRun.IsPresent | Out-Null
    }
} catch {
    Write-Log -Level 'ERROR' -Message ('Script failed: {0}' -f $_.Exception.Message)
    throw
}